FROM python:3.11.6

RUN pip install mysql-compare==0.0.17 -i https://mirrors.aliyun.com/pypi/simple/

WORKDIR /app/

COPY dbrepair.py .
COPY dbcompare.py .
COPY entrypoint.sh .

WORKDIR /log

CMD /bin/bash /app/entrypoint.sh